### PR TITLE
PR for #66: Update run_latex() to delete latex_auxiliary_dir

### LINKED ISSUE #66: Upgrade run_latex() to delete latex_auxiliary_dir when run the project
Follows https://github.com/gentzkow/template/issues/87#issuecomment-1783938127.

This issue is opened to implement an easy upgrade in [run_latex()](https://github.com/gslab-econ/gslab_make/blob/c08d6254f94f259ebd6d0cad994979911ab578c6/gslab_make/run_program.py#L212) function, to make it check whether directory `latex_auxiliary_dir` exists in the beginning, and if it exists, delete it.

### PR DESCRIPTION
**Pull request by ShiqiYang2022**
Closes #66.

In #66 I implement an easy upgrade in [run_latex()](https://github.com/gslab-econ/gslab_make/blob/c08d6254f94f259ebd6d0cad994979911ab578c6/gslab_make/run_program.py#L212) function, to make it check whether directory `latex_auxiliary_dir` exists in the beginning, and if it exists, delete it.

Per conversation, @jc-cisneros will review this PR. To check whether this branch is ready to merge, please populate this issue branch `gslab_make` to `template` and test the full run. Thanks!

### CODE REVIEW

**Comment by jc-cisneros** [comment]
Thanks @ShiqiYang2022! Will test this and keep you posted.

**Comment by jc-cisneros** [comment]
Status:
- First test: Opened `master` in template. I checked out this `gslab_make` development branch. I ran `run_all.py` and it generated `latex_auxiliary_dir` when it made it to `paper_slides`. However, it got stuck here:
```
Executing command: `latex -output-directory=../latex_auxiliary_dir  "/Users/jccp/Documents/template/paper_slides/code/paper.tex"`
```
- Second test: Shifted to the master branch of `gslab_make`, and `run_all.py` got stuck at exactly the same point. 

@ShiqiYang2022 do you have a sense of what might be going on?

**Review by jc-cisneros — APPROVED** [review]
Confirming this worked on my end on a fresh copy of template. Thanks for the work, @ShiqiYang2022!

**Comment by ShiqiYang2022** [comment]
Thanks @jc-cisneros for all the testing! Merging it back.

**Pull request merged**
