### PR TITLE
PR for #64: Upgrade run_latex to support nested .tex structure compiling

### LINKED ISSUE #64: Upgrade run_latex() to support nested .tex structure compiling
Follows https://github.com/gentzkow/template/issues/86.

This issue aim to upgrade `run_latex()` function to support nested `.tex` structure compile. Currently, when we run `run_latex()` to compile the nested `.tex` file structure, the main `.tex` file must live in the same path of `make.py`. 

But in [template](https://github.com/gentzkow/template), the `paper.tex` file lives in the `paper_slides/code/` folder, different from `paper_slides/` where `make.py` lives in. So we need to upgrade `run_latex()` to first execute command to navigate to same directory of main `.tex` file, and then execute the `.tex` compile code.

### PR DESCRIPTION
**Pull request by ShiqiYang2022**
Closes #64 .

This PR aim to review the upgrading in [`run_latex()`](https://github.com/gslab-econ/gslab_make/blob/301152d384a2571e03d853ccc9216c179d47a57e/gslab_make/run_program.py#L212) function and the corresponding [`metadata`](https://github.com/gslab-econ/gslab_make/blob/301152d384a2571e03d853ccc9216c179d47a57e/gslab_make/private/metadata.py#L22) to support nested `.tex` structure compiling. See https://github.com/gslab-econ/gslab_make/issues/64#issue-1948334180 and https://github.com/gentzkow/template/issues/86 for further details.

Per conversation, @snairdesai is requested to review. To test the upgraded version, please populate this issue branch `gslab_make` to the development [branch](https://github.com/gentzkow/template/tree/00259b931f4100ee99b05d17e1cc991362dc2eb0) of https://github.com/gentzkow/template/issues/86 and test the full run. Thanks!

### CODE REVIEW

**Comment by snairdesai** [comment]
Thanks @ShiqiYang2022! I'm having issues with the new branch of `gslab_make` here. See the screenshot below from when I attempt to run `template`:

Screenshot 2023-10-18 at 1 26 17 PM

I've confirmed I'm in the correct development branch here with the latest commits above incorporated:

Screenshot 2023-10-18 at 1 28 17 PM

**Comment by snairdesai** [comment]
_Update:_ Per conversation with @ShiqiYang2022, this is probably a new conflict arising from the Mac `M2` chip on my local machine. Even the standard `template` is no longer compiling on my local machine (though it did previously) which suggests something was updated in the `conda` environment which is no longer supported by Apple Silicon.

A new issue will be opened to address this; in the meantime @jc-cisneros will take over testing here.

**Comment by ShiqiYang2022** [comment]
@snairdesai Thanks for testing! I have requested @jc-cisneros to test this on his Macbook with intel chip.

**Comment by ShiqiYang2022** [comment]
@snairdesai In the intake issue of Lawence, how did you fix this incompatibility problem in https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009? I think you manually download `import.util` package. Could you please try rerun the `template` after you manually pull the package? Thanks!

**Comment by snairdesai** [comment]
Thanks @ShiqiYang2022, I think Lawrence implemented a hot fix -- as you note he had manually installed the `import.util` package to his local computer before building the `conda` environment. This is not the approach we want to take to fix this in `template`, though (this would defeat the point of the `conda` environment to begin with). I'm less keen to download this locally for this reason, though I can still do so if you'd like to ensure this PR works.

Given our investigations today, I think we can safely isolate the problem to a package conflict with `util` in the `conda` environment for the Apple Silicon chips. If you agree this is the case, I vote we resolve this directly in `conda` in a new issue rather than manually downloading this package.

**Comment by ShiqiYang2022** [comment]
@snairdesai Thanks!

@jc-cisneros Given https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1770008781 and your testing results, are you ready to approve this PR? Thanks!

**Comment by jc-cisneros** [comment]
@ShiqiYang2022 @snairdesai can you clarify what package is creating the conflict? From the screenshot in `https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009`, I thought it was `importlib`. I do agree that fixing this is out of the scope of this issue, so I will approve the changes here. @ShiqiYang2022 @snairdesai let's open a follow-up issue to pin down what is causing the error and come up with a systematic way to fix it (even if that means adding the "hot fix" to the instructions on template).

**Review by jc-cisneros — APPROVED** [review]

**Comment by ShiqiYang2022** [comment]
@jc-cisneros Thanks! I agree a new issue to address is necessary and this is already on my plate -- will open this soon -:)

**Comment by ShiqiYang2022** [comment]
Issue per https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009 opened in https://github.com/gentzkow/template/issues/89.

**Pull request merged**
