### PR TITLE
PR for #35 remove wait() from execute_command

### LINKED ISSUE #35: Fix hanging on execute_command
Follows [issue 261 in PhoneAddiction](https://github.com/gentzkow/PhoneAddiction/issues/261).

When running many bootstrap iterations in R for the PhoneAddiction repo, we found that the R files ran correctly when run using `RScript`, but hung and did not complete when run using `gslab.run_r`. The diagnosis for this appears to be the [`process.wait()` statement](https://github.com/gslab-econ/gslab_make/blob/771ea211f0bed9d6556f7ec6dae8527dd5eecdba/gslab_make/private/programdirective.py#L115), which may block if pipes overflow. From the documentation,

> Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

This StackOverflow discussion offers another explanation of [the difference between wait and communicate](https://stackoverflow.com/questions/12965023/python-subprocess-popen-communicate-equivalent-to-popen-stdout-read).

The best fix appears to be simply removing the `process.wait()` line, as the subsequent `process.communicate()` line [already calls wait internally](https://stackoverflow.com/questions/44456996/does-popen-communicate-implicitly-call-popen-wait). The one concern is that `communicate()` cannot handle output which is too large to be buffered in memory. ("Too large" is on the order of [gigabytes](https://stackoverflow.com/questions/6880090/alternatives-to-python-popen-communicate-memory-limitations) or [many megabytes](https://stackoverflow.com/questions/1180606/using-subprocess-popen-for-process-with-large-output) here). Since our outputs are mostly R logs, though, it seems that `communicate()` should be sufficient for our purposes.

Task list
- [x] Remove `process.wait()` from `Directive.execute_command()`

@Houdanait tagging you here if you have any other thoughts on wait vs communicate!

### PR DESCRIPTION
**Pull request by Etang21**
Closes #35.

This PR removes a call to `process.wait()` from `programdirective.py`, which can deadlock when running programs with large output. The `wait()` functionality is still achieved by the subsequent call to `communicate()`.

Testing: I have run all tests in the repository's `test` folder which are not currently excluded, and these tests pass.

### CODE REVIEW

**Comment by Houdanait** [comment]
Hi @Etang21, thank you for these! Would you mind explaining to me what is the purpose of your commit e0ce285? i'm not  familiar with the syntax of the file but I would like to understand.

**Comment by Etang21** [comment]
@Houdanait this is strange, I never made a commit about package documentation or Sphinx ... it seems like it's an automated commit, let me look into it real quick.

**Comment by Etang21** [comment]
@Houdanait so it looks like that code is an automatically generated commit which updates the project documentation when we change the code. From the [commit history on master](https://github.com/gslab-econ/gslab_make/commits/master), I think it has automatically updated documentation when Zane and Zong pulled in their changes too. This [README](https://github.com/gslab-econ/gslab_make/tree/master/sphinx) also links to some explanations.

Let me know if that seems right! Neat thing to learn about today.

**Comment by Houdanait** [comment]
@Etang21 I read over the documentation you linked through the ReadMethank you so much! 
I think we are good to merge.

**Summary of this issue.**
To keep everything concise here we had similar issues (hanging commands, even though they should run) which I believe can be linked to `process.wait()` In #33 and #34 we proposed a modification (to have a timeout within` process.wait()`) which should have fixed these issues but could not compile under Python 2.7
Hopefully, removing this command will solve the hanging issues in latex and matlab. 

In the `Gentzkow/PhoneAddiction` project, we realised that this command `process.wait()` led to sleeping processes, see this [comment](https://github.com/gentzkow/DigitalAddiction/issues/261#issuecomment-827222015). Some further reading suggested that it is interchangeable with `process.communicate()` which is already implemented in `program_directive.py`. Consequently we deleted the call to `process.wait()` in commit 97ba19f and was merged to master in commit ce2593d.

**Comment by Etang21** [comment]
@Houdanait looks great; thanks so much for approving the PR and merging it in!

**Pull request merged**
