### PR TITLE
PR for #62: Revert Accidental Commit

### LINKED ISSUE #62: Revert Accidental Commit
This issue aim to revert one accidental commit to `gslab_make`. 

@ShiqiYang2022 was trying to refer [gslab_make](https://github.com/gslab-econ/gslab_make) as a submodule in one of his personal repository, using `git submodule add`. He commited the change(this reference to [gslab_make](https://github.com/gslab-econ/gslab_make)) to his personal repo via VSCode Git Extension. After that commit to his personal repo, an unintended commit(ref [here](https://github.com/gslab-econ/gslab_make/commit/2e7815d36cd8bad0f92c64d1eeadcc9399b4a141)) happened to the `master` branch of [gslab_make](https://github.com/gslab-econ/gslab_make).

Task list
- [x] Find out why accidental commit happened.
- [x] Revert Commit.

@ShiqiYang2022 plan to fix this, with @snairdesai providing support.

### PR DESCRIPTION
**Pull request by ShiqiYang2022**
Closes #62 .

The purpose of this PR is to revert commits flagged in #62.

@ShiqiYang2022 is assigned and @snairdesai is requested to review.

### CODE REVIEW

**Comment by ShiqiYang2022** [comment]
Note: after I opened this pull request, it automatically triggered [update-docs.yml](https://github.com/gslab-econ/gslab_make/blob/master/.github/workflows/update-docs.yml) in Github Action, and committed 04b8564. In this file, the purpose of the workflow is described as:

> This workflow will update documentation using Sphinx and push changes to the Github page.

I suggest the commit 04b8564 just did some minor updates in documentation due to the Github Action, and I think this can not be considered into the decision whether or not to merge.

**Review by snairdesai — APPROVED** [review]
Thanks @ShiqiYang2022! Your reversion looks fine to me. Did you check that the [website](https://gslab-econ.github.io/gslab_make/) still builds as expected? I think we might need to merge back to `main` first for `GitHub` actions to automate the build.

**Comment by ShiqiYang2022** [comment]
@snairdesai Thank! The [website](https://gslab-econ.github.io/gslab_make/) worked well.

**Comment by ShiqiYang2022** [comment]
**Summary**

This PR reverted commits flagged in https://github.com/gslab-econ/gslab_make/issues/62.

**Pull request merged**
