### PR TITLE
PR for #59: Remove archival jquery and duplicate files

### LINKED ISSUE #59: Remove archival jquery and duplicate files
The purpose of this issue (#59) follows from @gentzkow's `dependabot` flag relating to `jquery`:

Screen Shot 2023-04-04 at 2 06 06 PM

It seems the only step here should be updating `jquery` to its latest version, and ensuring `gslab_make` still works as intended following the update. @snairdesai and @jc-cisneros have been assigned. The relevant development branch is [`issue59_jquery`](https://github.com/gslab-econ/gslab_make/tree/issue59_jquery).

### PR DESCRIPTION
**Pull request by snairdesai**
Closes #59.

The purpose of this PR follows from a `dependabot` flag relating to `jquery`:

Screen Shot 2023-04-04 at 2 06 06 PM

This flag relates to an archival documentation file in [`~/docs/_static`](https://github.com/gslab-econ/gslab_make/tree/master/docs/_static) for version `3.2.1` of `jquery`. To remedy this flag, we have deleted this file from the `docs` subfolder. As part of this issue, we also noticed a series of duplicate files were unintentionally created as part of a prior PR, and have deleted these duplicates.

The relevant development branch is [`issue59_jquery`](https://github.com/gslab-econ/gslab_make/tree/issue59_jquery). @jc-cisneros has been assigned as a reviewer. To review this PR, please complete the following steps:

- [x] Confirm the statement made in [this comment](https://github.com/gslab-econ/gslab_make/issues/59#issuecomment-1496651946), and ensure that version `3.2.1` of `jquery` does not support any underlying modules in `gslab_make.`
- [x] Ensure the correct duplicate files were removed in [this commit](https://github.com/gslab-econ/gslab_make/commit/e5695663db766f5965580b907d4bfc5f96fa2577), and that no other duplicates remain in the `repo`.
- [x] Check that the removal of **(1)** `~/docs/_static/jquery-3.2.1.js` and **(2)** the duplicate files mentioned above do not affect `gslab_make`.

### CODE REVIEW

**Comment by snairdesai** [comment]
_Update:_ The unit tests which were expected to pass did (Python `2.7` has been unsupported for some time, we may want to open a new issue at some point to remove this test), but it seems the `~/docs/_static/jquery-3.2.1.js` was automatically re-added. This suggests we'll need to address this file in the unit tests themselves (thankfully, no duplicate files were created this time).

**Comment by snairdesai** [comment]
@jc-cisneros I think I was able to properly navigate the unit tests in the commit above ([`cabb91e`](https://github.com/gslab-econ/gslab_make/pull/60/commits/cabb91e29a2a4925e164988627d5bcbfcd654024)). This should be ready for your review, let me know your thoughts!

**Review by jc-cisneros — CHANGES_REQUESTED** [review]
Thanks for the work here @snairdesai! I think you effectively removed all the duplicated files. The relevant [build test (Python 3.7)](https://github.com/gslab-econ/gslab_make/actions/runs/4623399034/jobs/8177167572) was passed and the jquery version that was flagged as vulnerable was removed. My only concern left is that many of the `html` scripts were updated automatically and we are not able to check if the documentation website is still built as intended without involving `master`. My proposal is that we proceed with this merge and open two new follow-up issues. One issue can be focused on updating the documentation website. Aside from checking that these automatic changes did not alter the format in any undesirable way, we need to add entries for all the last updates in the package (e.g., using Julia). The second issue can be focused on updating the build tests that are triggered by GitHub actions. In particular, the current version of `gslab_make` fails the test with Python 2.7. I think we can remove that test and add one for Python 3.11 (in addition to the Python 3.7 test). @snairdesai let me know what you think.

**Comment by snairdesai** [comment]
@jc-cisneros Agreed, all of this makes sense to me. As you note, updating the unit tests and website documentation is outside the scope of this issue, but is relevant to address in new issues. If you approve, I'll proceed to merge back to `master`, while leaving this development branch alive, to check is the website build remains stable.

**Review by jc-cisneros — APPROVED** [review]
@snairdesai I agree with https://github.com/gslab-econ/gslab_make/pull/60#issuecomment-1498289126. This looks good to merge. We can take a look at the website right after that has been done. Thanks again!

**Pull request merged**
