### PR TITLE
PR for #41:  Default config file for update_paths

### LINKED ISSUE #41: Default config file for update_paths
Follows [comment](https://github.com/gentzkow/template/issues/40#issuecomment-897133642) of [issue](https://github.com/gentzkow/template/issues/40).

The purpose of this issue is to change how config files are loaded. We want to update paths using two config files: the default one and a second one which users can use to override default settings.

Task list
- [x] Change to [make_utility.py](gslab_make/make_utility.py) in accordance with guidance given [here](https://github.com/gentzkow/template/issues/40#issuecomment-897207031).

### PR DESCRIPTION
**Pull request by szahedian**
Closes #41.

Executable names moved to default `config.yaml`. Executable names can be overridden using `config_user.yaml`. 

Backward compatible with storing executable names in `config_user.yaml`.

### CODE REVIEW

**Comment by jc-cisneros** [comment]
@gentzkow I assigned myself as a reviewer to double check the backwards compatibility. 

I tested these changes on the `master` branch of template and got the following error:

```
(template) SIEPR-C02D90E2ML85:template jccp$ python run_all.py
WARNING! config.yaml does not include default executable names.
Traceback (most recent call last):
  File "/Users/jccp/Documents/template/run_all.py", line 25, in <module>
    gs.update_executables(PATHS)
  File "/Users/jccp/Documents/template/./lib/gslab_make/gslab_make/make_utility.py", line 87, in update_executables
    write_to_makelog(paths, message)
  File "/Users/jccp/Documents/template/./lib/gslab_make/gslab_make/write_logs.py", line 140, in write_to_makelog
    makelog = get_path(paths, 'makelog')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jccp/Documents/template/./lib/gslab_make/gslab_make/private/utility.py", line 91, in get_path
    raise_from(CritError(messages.crit_error_no_key % (key, key)), None)
  File "/usr/local/Caskroom/miniconda/base/envs/template/lib/python3.11/site-packages/future/utils/__init__.py", line 406, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
gslab_make.private.exceptionclasses.CritError: 
ERROR! Argument `paths` is missing a value for key `makelog`. Add a path for `makelog` to your paths dictionary.
```

The solution proposed in the `make_utility.py` is not coherent with the current structure in template. This would require changes in template (and the documentation). Given that the added benefit would be not having to include a `config_user.yaml` only in cases where [_no dependencies are required_](https://github.com/gslab-econ/gslab_make/issues/41#issuecomment-899751202), my vote would be to close without a merge to master (and no changes to template). 

@snairdesai @gentzkow let me know what you think. If you agree I will write a summary comment in #41, create an stable link in case we want to revisit the way we deal with the config paths in `template`, and close both #41 and #42.

**Comment by gentzkow** [comment]
Thanks @jc-cisneros.

I still like the idea of having a default set of executable names in `config.yaml` so that these only have to be included in `config_user.yaml` in the (relatively rare) cases where a user wants to override them. I would have thought this would be straightforward to implement. If you think it's not straightforward, can you say a little more about why?

**Comment by gentzkow** [comment]
(This might be a good task to hand off to @ShiqiYang2022 to help him get familiar with [gslab_make](https://github.com/gslab-econ/gslab_make).)

**Comment by jc-cisneros** [comment]
@gentzkow I agree with your comment in https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1638044828 (always in favor of changes that make the workflow easier for the user). Nevertheless, I think this new feature does not add a lot more value relative to the "cost" of implementing it. Let me clarify on both the benefits and costs:
1) The purpose of this new feature is that users don't have to go through the small hassle of having to manually configure the executable names in `config_user.yaml` and moving it to the root of the repository. This solution would only provides that benefit in the case that the user does not have any external dependencies (i.e., paths to Dropbox or private directories). If that is not the case, the user would still need to manually edit `config_user_template.yaml` and move it to the root of the directory. Given that the default executables are already defined in `config_user_template.yaml`, I don't see how this change can make the users' setup process easier.
2) While the changes on this branch pass the unit tests, they do not include the changes implemented in #48 and some changes would also be required on `template` (e.g., adding `future` to the conda environment requirements, or adding the default executable names to `config.yaml`). While these are relatively straightforward changes, they would imply extra work on both repositories and in the documentation. 

Given that (1) does not add that much value relative to the status quo, I am not sure if it is worth having @ShiqiYang2022 working on (2). @gentzkow @snairdesai let me know what you think and we can decide how to proceed based on that.

**Comment by gentzkow** [comment]
ok! happy to set it aside for now; maybe we can just make a note on the project outline on the wiki to consider pursuing later

**Comment by jc-cisneros** [comment]
Perfect @gentzkow! I added a note to the [Project Outline](https://github.com/gentzkow/template/wiki/Project-Outline). Will reproduce the note below as a reference:

> Replace the current config.yaml/config_user.yaml logic to reduce extra steps for users that will adhere to defaults. Per [this comment](https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1638696617), that would imply finding a solutions that can implement default values both for external directories (i.e., the default external directory is the Dropbox directory within the user's system) and executable names.

Per https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1648095892 and our conversation, we will prioritize making template (and its Workflow) fully compatible with Overleaf and can then go over the [other To-do tasks](https://github.com/gentzkow/template/wiki/Project-Outline) that would improve the user's experience if there is bandwidth.

cc. @snairdesai @ShiqiYang2022

**Pull request closed without merging**
