### PR TITLE
PR for #16: Refactor tablefill and textfill

### LINKED ISSUE #16: Refactor tablefill and textfill
Goals:

1. Port `tablefill` and `textfill` for Python 3
2. Refactor `tablefill` and `textfill` to make codebase more Pythonic and transparent

I would focus on completing (1) then moving on to (2). I had started on (1) with [this commit](https://github.com/gentzkow/gslab_make/commit/3171dfaddc633d6934881b6d9e69b890df3b1f51) but never actually tested to see if everything was working correctly on Python 3.

I would branch off [issue13_template_to_dos](https://github.com/gentzkow/gslab_make/tree/issue13_template_to_dos).

### PR DESCRIPTION
**Pull request by z-y-huang**
Closes #16.

First attempt to refactor `textfill`. Note that `textfill` has been deprioritized as we have a new method for filling in scalars in LyX documents. (See [RA manual](https://github.com/gentzkow/ra-manual/wiki/Allcott-Gentzkow-Lab-Notes) for more details.)

### CODE REVIEW

**Comment by jc-cisneros** [comment]
@jmshapir @gentzkow  should we close this PR without a merge to master? As a reminder, the goal of this [issue from February, 2019](https://github.com/gslab-econ/gslab_make/issues/16#issue-415760757) was the following:

```
Goals:

1. Port `tablefill` and `textfill` for Python 3
2. Refactor `tablefill` and `textfill` to make codebase more Pythonic and transparent
```

Per my understanding, both of these functions do work with Python 3 and are very LyX-specific. I am not sure what the "new method for filling in scalars in LyX documents" referenced in the [description of the PR](https://github.com/gslab-econ/gslab_make/pull/30#issue-631134002) is. If we needed to refactor tablefill and textfill, I would suggest a non-LyX solution like [AutoFill](https://github.com/gslab-econ/gslab_r/blob/2f5d3ac582cec5aa2a29350582059ce4076137a8/GSLabMisc/R/AutoFill.R) .

**Comment by jmshapir** [comment]
@jc-cisneros that would be fine with me, thanks. In that case I think we would want to grab a stable link to the state of the branch prior to deletion (and include it in the summary comment) in case we ever want to point back to the work on the branch.

Thanks!

**Comment by gentzkow** [comment]
OK by me too

**Comment by jc-cisneros** [comment]
Per https://github.com/gslab-econ/gslab_make/pull/30#issuecomment-1636587464 and https://github.com/gslab-econ/gslab_make/pull/30#issuecomment-1636825918, we closed this PR without merging to master.

Find a summary of the issue and a stable link to the last version of the development branch [here](https://github.com/gslab-econ/gslab_make/issues/16#issuecomment-1637156180).

cc. @jmshapir @gentzkow

**Pull request closed without merging**
