### PR TITLE
PR for #54 Create run_julia wrapper

### LINKED ISSUE #54: Create run_julia wrapper
Per https://github.com/gentzkow/CommitFlex/issues/112#issuecomment-1262897169, we could add support for Julia in the gslab_make module. Tests will be run in `template`(see https://github.com/gentzkow/template/issues/67)

Task list
- [x] Create new branch and create a first version of the wrapper.
- [x] Test on [template/67-julia-extension branch](https://github.com/gentzkow/template/tree/67-julia-extension)

### PR DESCRIPTION
**Pull request by jc-cisneros**
This pull request closes #54. The way to test the new run_julia wrapper is described in https://github.com/gentzkow/template/pull/68.

### CODE REVIEW

**Comment by jc-cisneros** [comment]
I also want to flag that the unit tests failed (see https://github.com/gslab-econ/gslab_make/actions/runs/3230092659/jobs/5288141596#step:5:368) because the test scripts were expecting the files with the extraneous characters (i.e., `move_╬▓.txt`) that were not compatible with the new Julia-capable conda environment. I will take a look at the test scripts and load the correct files.

**Comment by jc-cisneros** [comment]
A follow-up to the previous comment:

The error occurs when `template_julia` is active (the only difference with `template` is that it has Julia installed). The following screenshot is the error message I get when running `python run_all.py` with the `master` branch of the `gslab_make` submodule:
 
Screen Shot 2022-10-11 at 2 27 43 PM

This error is also reported on this [issue on the conda-forge GitHub](https://github.com/conda-forge/git-feedstock/issues/50). The `template` environment is using my local git installation, so the error is surely related to the MAC git discussed in the conda-forge issue. Julia's source code lives on GitHub, so it requires git as a dependency in the conda environment.  Indeed the error is reproduced if `-git` is added to the `template` environment. Therefore we have the following choices:
- Removing the git package from the conda environment and use the local version. This is the current default in template (i.e., installing git locally and not on the conda environment). A possible caveat is that the "local" git might produce the same error in other OS. 
- Adding the git package to the conda environment and removing both the files with extraneous characters and the gslab_make unit tests that tested the capacity to catch these characters. 

I am inclined towards the second option, as any errors related to unicode/ASCII characters would be caught by git. Let me know what you think @gentzkow @snairdesai.

**Comment by snairdesai** [comment]
@jc-cisneros Seems you already tackled this, but I second that option **(2)** [above](https://github.com/gslab-econ/gslab_make/pull/55#issuecomment-1275342521) makes intuitive sense.

**Comment by snairdesai** [comment]
Pending revisions to `gentzkow` [#68](https://github.com/gentzkow/template/pull/68#pullrequestreview-1151394513) based on my latest review, this looks good to go @jc-cisneros!

**Review by snairdesai — APPROVED** [review]
Per revisions to [#68](https://github.com/gentzkow/template/pull/68) in `gentzkow/template`, this looks good to go. Thanks @jc-cisneros!

**Pull request merged**
